function F = Hamilton(X, coef, p, I, J) 
% Hamilton calculates the Hamiltonian system's entries.
    lc = coef(I, J, 1) +...
        coef(I, J, 2) * (X(1) - p(I)) + ...
        coef(I, J, 3) * (X(2) - p(J)) + ...
        coef(I, J, 4) *  (X(1) - p(I)) * ( (X(2) - p(J)) );
    
    lgc = [coef(I, J, 2) + coef(I, J, 4) *  ( (X(2) - p(J)) )  ...
           coef(I, J, 3) + coef(I, J, 4) *  ( (X(1) - p(I)) )];
    
    F = [lc^2 * X(3:4) -lgc * lc * (X(3:4)*X(3:4)')];
end